clear all

% input the data
filename = 'C:\Users\Jiacheng Zheng\Desktop\test.xlsx';
sheetname0= 'Sheet1';

data_x = readtable(filename, 'Sheet', sheetname0, 'Range', 'D17:H17');
x = table2array(data_x);


data_z = readtable(filename, 'Sheet', sheetname0, 'Range', 'D4:H8');
z = table2array(data_z);

data_y = readtable(filename, 'Sheet', sheetname0, 'Range', 'I4:M8');
y = table2array(data_y);

f=sum(y,2);

A=z./x;

% page 10
DBL=sum(A,1); % Direct backward linkage

% page 12
I=eye(size(A));
L=inv(I-A); 

% page 13
TBL=sum(L,1); % Total backward linkage

% page 14
CGO=sum(A,2); % change in the gross output of all the sectors
CFD=sum(L,2); % change in the final demand of all the sectors


% page 15
B=z./x';
DFL=sum(B,2); % Direct forward linkage

% page 16
G=inv(I-B);
TFL=sum(G,2); % Total forward linkage

% page 17
n=5;
for j=1:n
NDBL{j}=DBL(:,j)./(DBL./n); % Normalized direct backward linkage
end

for j=1:n
NTBL{j}=TBL(:,j)./(TBL./n) ;% Normalized total backward linkage 
end

% page 18
for j=1:n
NDFL{j}=DFL(j,:)./(DFL./n); % Normalized direct forward linkage
end

for j=1:n
NTFL{j}=TFL(j,:)./(TFL./n); % Normalized total forward linkage
end

% page 21
LF=L*diag(f); % Lf is a matrix whose (i, j)th element represents output of sector i generated by fj, final demand of sector j
NBL=sum(LF,1)./sum(LF,2)';

