function divConresult
AFG = z();
ALB
DZA
AND
AGO
ATG
ARG
ARM
ABW
AUS
AUT
AZE
BHS
BHR
BGD
BRB
BLR
BEL
BLZ
BEN
BMU
BTN
BOL
BIH
BWA
BRA
VGB
BRN
BGR
BFA
BDI
KHM
CMR
CAN
CPV
CYM
CAF
TCD
CHL
CHN
COL
COG
CRI
HRV
CUB
CYP
CZE
CIV
PRK
COD
DNK
DJI
DOM
ECU
EGY
SLV
ERI
EST
ETH
FJI
FIN
FRA
PYF
GAB
GMB
GEO
DEU
GHA
GRC
GRL
GTM
GIN
GUY
HTI
HND
HKG
HUN
ISL
IND
IDN
IRN
IRQ
IRL
ISR
ITA
JAM
JPN
JOR
KAZ
KEN
KWT
KGZ
LAO
LVA
LBN
LSO
LBR
LBY
LIE
LTU
LUX
MAC
MDG
MWI
MYS
MDV
MLI
MLT
MRT
MUS
MEX
MCO
MNG
MNE
MAR
MOZ
MMR
NAM
NPL
NLD
ANT
NCL
NZL
NIC
NER
NGA
NOR
PSE
OMN
PAK
PAN
PNG
PRY
PER
PHL
POL
PRT
QAT
KOR
MDA
ROU
RUS
RWA
WSM
SMR
STP
SAU
SEN
SRB
SYC
SLE
SGP
SVK
SVN
SOM
ZAF
SDS
ESP
LKA
SUD
SUR
SWZ
SWE
CHE
SYR
TWN
TJK
THA
MKD
TGO
TTO
TUN
TUR
TKM
USR
UGA
UKR
ARE
GBR
TZA
USA
URY
UZB
VUT
VEN
VNM
YEM
ZMB
ZWE
ROW


NBRI = AND + ABW + AUS + BHS + BEL + BLZ + BMU + BTN + BRA + VGB + CAN + CYM + CAF + COL + DNK + FIN + FRA + PYF + DEU + GRL + GTM + HTI + ISL + IND + IRL + ISR + JPN + KAZ + LIE + MUS + MEX + MCO + NLD + ANT + NCL + NOR + PSE + PRY + SMR + ESP + SWZ + SWE + CHE + TUR + USR + GBR + USA + VNM + ROW;

BRI = AFG + ARM + ARG + BHR + BGD + BRN + KHM + CHN + PRK + GEO + GHA + IDN + IRN + IRQ + JOR + KWT + KGZ + LAO + LBN + MYS + MDV + MNG + MMR + NPL + OMN + PAK + PHL + QAT + KOR + SAU + SGP + LKA + SYR + TJK + THA + TKM + ARE + UZB + YEM + DZA + AGO + BEN + BWA + BFA + BDI + CMR + CPV + TCD + COG + CIV + COD + DJI + EGY + ERI + ETH + GAB + GMB + GIN + KEN + LSO + LBR + LBY + MDG + MWI + MLI + MRT + MAR + MOZ + NAM + NER + NGA + RWA + STP + SEN + SYC + SLE + SOM + ZAF + SDS + SUD + TGO + TUN + UGA + TZA + ZMB + ZWE + ALB + AUT + BLR + BIH + BGR + HRV + CYP + CZE + EST + GRC + HUN + ITA + LVA + LTU + LUX + MLT + MNE + POL + PRT + MDA + ROU + RUS + SRB + SVK + SVN + MKD + UKR + ATG +  BRB +  CRI +  CUB +  DOM +  SLV +  HND +  JAM +  NIC +  PAN +  TTO + AZE +  BOL +  ECU +  GUY +  PER +  SUR +  URY +  VEN +  CHL + FJI +  NZL +  PNG +  WSM +  VUT;

BRIASIA = AFG + ARM + ARG + BHR + BGD + BRN + KHM + CHN + PRK + GEO + GHA + IDN + IRN + IRQ + JOR + KWT + KGZ + LAO + LBN + MYS + MDV + MNG + MMR + NPL + OMN + PAK + PHL + QAT + KOR + SAU + SGP + LKA + SYR + TJK + THA + TKM + ARE + UZB + YEM;

BRIAFRICA = DZA + AGO + BEN + BWA + BFA + BDI + CMR + CPV + TCD + COG + CIV + COD + DJI + EGY + ERI + ETH + GAB + GMB + GIN + KEN + LSO + LBR + LBY + MDG + MWI + MLI + MRT + MAR + MOZ + NAM + NER + NGA + RWA + STP + SEN + SYC + SLE + SOM + ZAF + SDS + SUD + TGO + TUN + UGA + TZA + ZMB + ZWE;

BRIEUROPE  =  ALB + AUT + BLR + BIH + BGR + HRV + CYP + CZE + EST + GRC + HUN + ITA + LVA + LTU + LUX + MLT + MNE + POL + PRT + MDA + ROU + RUS + SRB + SVK + SVN + MKD + UKR;

BRINORTH_AMERICA = ATG +  BRB +  CRI +  CUB +  DOM +  SLV +  HND +  JAM +  NIC +  PAN +  TTO;

BRISOUTH_AMERICA = AZE +  BOL +  ECU +  GUY +  PER +  SUR +  URY +  VEN +  CHL;

BRIOCEANIA = FJI +  NZL +  PNG +  WSM +  VUT;


return 
end